name: test nix

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-25.05
    - uses: actions/checkout@v4
      with:
        path: current
    - name: Run the test.nix
      run: nix-build test.nix
      working-directory: current/

